version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: mutation-browser-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16
    container_name: mutation-browser-postgres
    environment:
      POSTGRES_DB: mutation_browser
      POSTGRES_USER: mutation_user
      POSTGRES_PASSWORD: mutation_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: shalabhsuman/mutation-browser-api:0.1.0
    container_name: mutation-browser-api
    depends_on:
      - rabbitmq
      - postgres
    environment:
      DB_NAME: mutation_browser
      DB_USER: mutation_user
      DB_PASSWORD: mutation_pass
      DB_HOST: postgres
      DB_PORT: 5432
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    ports:
      - "8000:5000"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: shalabhsuman/mutation-browser-api:0.1.0
    container_name: mutation-browser-celery-worker
    depends_on:
      - rabbitmq
      - postgres
    environment:
      DB_NAME: mutation_browser
      DB_USER: mutation_user
      DB_PASSWORD: mutation_pass
      DB_HOST: postgres
      DB_PORT: 5432
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    command: celery -A backend.celery_app.celery_app worker --loglevel=info

volumes:
  postgres_data:
